name: SQL tests

on: 
  push:
    paths:
      - 'Modules/M3_SQL/**'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
    - name: Install Dependencies
      run: |
        pip install pandas
        pip install pytest
    - name: PyTest
      run: |
        pytest -v Modules/M3_SQL/tests/test.py
          
